### PR TITLE
Zygote Batch Support

### LINKED ISSUE #37: Zygote producing wrong result for ndim >1 & batch > 0
Only 1st element in the gradient is wrong and it is scaled exactly by the batchsize. NOTE: that the batchsize is determined by the internal algorithm and `batch=10` is just a hint. In this following example the batchsize is 17. 136/17=8, where 8 is the correct answer

```julia
using Quadrature, Cuba, Cubature, Zygote, FiniteDiff, ForwardDiff, Test

f(x,p) = x[1,:]*p[1].+p[2]*p[3]

lb =[1.0,1.0]
ub = [3.0,3.0]
p = [2.0, 3.0, 4.0]
prob = QuadratureProblem(f,lb,ub,p)

function testf3(lb,ub,p; f=f)
    prob = QuadratureProblem(f,lb,ub,p, batch = 10, nout=1)
    solve(prob, CubatureJLh(); reltol=1e-3,abstol=1e-3)[1]
end

dp1 = ForwardDiff.gradient(p->testf3(lb,ub,p),p)
dp2 = Zygote.gradient(p->testf3(lb,ub,p),p)[1]
dp3 = FiniteDiff.finite_difference_gradient(p->testf3(lb,ub,p),p)

@test dp1 ≈ dp3 # passes
@test_broken dp2 ≈ dp3 # Fail  [136,16,12] ≈ [9,16,12]
```

### PR DESCRIPTION
**Pull request by agerlach**
Closes #37

### CODE REVIEW

File: src/Quadrature.jl [hunk 1]
```diff
@@ -403,22 +403,35 @@ ZygoteRules.@adjoint function __solvebp(prob,alg,sensealg,lb,ub,p,args...;kwargs
...
         else
             _f = (x) -> prob.f(x,p)
             if sensealg.vjp isa ZygoteVJP
-                dfdp = function (x,p)
-                    _,back = Zygote.pullback(p->prob.f(x,p),p)
-                    back(y)[1]
+                if prob.batch > 0
+                    dfdp = function (x,p)
+                        out = zeros(length(p),size(x,2))
+                        for idx in 1:size(x,2)
```
Comment (ChrisRackauckas) [inline src/Quadrature.jl:424]: I guess that gets it working, but there should be a better way to batch this?

Comment (agerlach) [reply src/Quadrature.jl:424]: Yeah, I saw this a low hanging fruit. I'm all ears on thoughts for a better approach.

Comment (ChrisRackauckas) [reply src/Quadrature.jl:424]: how is this not equivalent to the other one?

**Comment by ChrisRackauckas** [comment]
I'd be weary of merging this without figuring out how this is actually different: it looks like it's computing the same thing, just without the parallelism, which seems wrong.

**Comment by agerlach** [comment]
"wrong" as in there is a better way, or "wrong" as in incorrect? It is computing the same thing. It is equivelent to 
```
dfdp = function (x,p)
    _,back = Zygote.pullback(p->prob.f(x,p),p)
    back(y)[1]
end

if prob.batch > 0
    _dfdp = dfdp
    dfdp = function (x,p)
        out = zeros(length(p),size(x,2))
        for idx in 1:size(x,2)
            out[:,idx] .= _dfdp(@view(x[:,idx]),p)
        end
        out
    end
end
```

**Comment by ChrisRackauckas** [comment]
But the first is computing incorrect values right? I think it's best to figure out why, instead of trying to just avoid the issue.

**Comment by agerlach** [comment]
If you call 
```
dfdp = function (x,p)
    _,back = Zygote.pullback(p->prob.f(x,p),p)
    back(y)[1]
end
```
directly for batch >0 you will get incorrect answers. I seems like the issue is the size of `y`. It is odd, in some of the tests it will report the wrong answer, but in others it will error about dimensions. I *think* the difference between the two depended on if it was inplace or not.

**Comment by agerlach** [comment]
Here is a MWE showing the issue
```
using Zygote
w(x,p) = x[1,:]*p[1] + x[2,:]*p[2]
batch = 5
_,back  = Zygote.pullback(p->w(repeat([1,2],inner=(1,batch)),p),[3 2])
back([1])[1] #returns [5, 10]. but should return something like [1 1 1 1 1; 2 2 2 2 2]
```

File: src/Quadrature.jl [hunk 2]
```diff
@@ -403,22 +403,35 @@ ZygoteRules.@adjoint function __solvebp(prob,alg,sensealg,lb,ub,p,args...;kwargs
...
+                            _,back = Zygote.pullback(p->prob.f(@view(x[:,idx]),p),p)
```
Comment (agerlach) [inline src/Quadrature.jl:425]: Still feels like a hack, but the `pullback` can get taken out of the loop w/o the view and then loop through `back` accordingly. 

Using MWE:
```julia
using Zygote
w(x,p) = x[1,:]*p[1] + x[2,:]*p[2]
batch = 5
_,back  = Zygote.pullback(p->w(repeat([1,2],inner=(1,batch)),p),[3 2])

out = zeros(2, batch )
for idx in 1:batch
    z = zeros(batch)
    z[idx] = 1
    out[:,idx] = back(z)[1]
end
```

Comment (ChrisRackauckas) [reply src/Quadrature.jl:425]: You shouldn't need to pull back the pieces separately though: this is pullback of the identity matrix of a sparse Jacobian which is the matrix coloring problem that has a single color solution.

Comment (agerlach) [reply src/Quadrature.jl:425]: I'm not sure I understand.

Comment (ChrisRackauckas) [reply src/Quadrature.jl:425]:
```julia
using Zygote
w(x,p) = x[1,:]*p[1] + x[2,:]*p[2]
batch = 5
_,back  = Zygote.pullback(p->w(repeat([1,2],inner=(1,batch)),p),[3 2])

out = zeros(2, batch )
z = zeros(batch)
for idx in 1:batch
    z[idx] = 1
    out[:,idx] = back(z)[1]
    z[idx] = 0
end
out
```

is how I'd do it. It's not a hack but the right way to do it, because you have to pull back the basis elements if the function isn't sparse, and here it's not sparse in `p`. This keeps the primal calculation down to a single time and is the equivalent to the forwarddiff chunk version.

**Comment by agerlach** [comment]
This should reduce the primal calculation as we discussed for in and out of place. Currently crashes for `nout > 1`

**Review by ChrisRackauckas — APPROVED** [review]
